vendors:
  - name: OpenAI
    site: openai.com
    feeds:
      - https://openai.com/blog/rss.xml
    keywords: ["agent", "agents", "deep research", "governance", "actions", "mcp"]
    audience: "enterprise"
    impact: 5
    risk: 3

  - name: Microsoft
    site: learn.microsoft.com
    feeds:
      - https://learn.microsoft.com/api/feed/azure/ai/index.json
    keywords: ["agent", "agents", "Azure AI Foundry", "MCP", "monitor", "governance"]
    audience: "enterprise"
    impact: 5
    risk: 2

  - name: Google
    site: cloud.google.com
    feeds:
      - https://cloud.google.com/feeds/products.xml
      - https://cloud.google.com/blog/topics/ai-machine-learning/rss/
    keywords: ["agent", "agents", "Vertex", "Agent Builder", "Agent Engine"]
    audience: "enterprise"
    impact: 5
    risk: 2

  - name: AWS
    site: aws.amazon.com
    feeds:
      - https://aws.amazon.com/new/feed/
    keywords: ["agent", "agents", "Bedrock", "AgentCore", "guardrails", "memory"]
    audience: "enterprise"
    impact: 4
    risk: 3

  - name: LangChain
    site: blog.langchain.com
    feeds:
      - https://blog.langchain.com/feed
    keywords: ["langgraph", "multi-agent", "runtime", "platform", "ga"]
    audience: "dev"
    impact: 5
    risk: 2

  - name: Dify
    site: docs.dify.ai
    feeds:
      - https://docs.dify.ai/changelog.xml
    keywords: ["mcp", "agent", "workflow", "debugger"]
    audience: "dev"
    impact: 3
    risk: 2
