name: Update Agent Radar JSON

on:
  schedule:
    - cron: "0 0 * * *"   # 每天 00:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 feedparser pyyaml python-dateutil

      - name: Build & merge agent-radar.json
        run: |
          python scripts/build_agent_radar.py \
            --sources scripts/sources.yaml \
            --in data/agent-radar.json \
            --out data/agent-radar.json \
            --days 30 \
            --top 60

      - name: Commit & push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add data/agent-radar.json
          git commit -m "chore: auto-update agent-radar.json" || echo "no changes"
          git push

      - name: (optional) Slack notify
        if: ${{ secrets.SLACK_WEBHOOK_URL != '' }}
        run: |
          python scripts/build_agent_radar.py \
            --sources scripts/sources.yaml \
            --in data/agent-radar.json \
            --out /tmp/agent-radar.json \
            --notify "${{ secrets.SLACK_WEBHOOK_URL }}"
